### ISSUE TITLE
报错code 134.

### ISSUE THREAD

**Issue by Stella-360** [hjenryin/BCJH-Metropolis#11]
同步到最新版本后仍然报错134
![image](https://user-images.githubusercontent.com/123476029/214341024-81a9b6dd-ece4-4718-a95c-89255f51503e.png)

**Comment by hjenryin** [comment]
![image](https://user-images.githubusercontent.com/72179072/214373704-52473d10-c68f-4fc6-a002-09d60806a433.png)
破案了，我本来以为是git找不到文件到知道，然而之前我想的方向错了。
不知道为什么白菜菊花有两种格式，一种是字符串，一种是数字。我完全是按照数字来处理的，这也解释了为什么我从来没有问题，而有的朋友会遇到问题……

**Comment by hjenryin** [comment]
2306cdb6c1c49a950e9e726a669ac71bbc78852a
已更新

**Comment by Stella-360** [comment]
> [2306cdb](https://github.com/hjenryin/BCJH-Metropolis/commit/2306cdb6c1c49a950e9e726a669ac71bbc78852a) 已更新，再试试呢

已解决 感谢
