### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by shilaimu21** [hjenryin/BCJH-Metropolis#146]
按照那个自动更新指示，没有看到循环箭头。然后ACTIONS里面有166个指令，绿√和红×都有。这个得怎么搞，谢谢大佬

**Comment by shilaimu21** [comment]
因为不是更新关卡了吗，所以今天刚刚想上去算的，然后发现没地方更新。要不加下qq，1607243069



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上10:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjenryin/BCJH-Metropolis] 大佬求助 (Issue #146)




 
你使用的是这个账号吗？我看你上一次action是两天前的，没有看到最新一次的记录呀？

**Comment by hjenryin** [comment]
> 然后ACTIONS里面有166个指令，绿√和红×都有。

能截个图或者发个链接看眼吗？

**Comment by shilaimu21** [comment]
上次用完就没再用了，然后今天想用就出现了这些，大佬看看。
图片只能用大小小一点的了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjenryin/BCJH-Metropolis] 大佬求助 (Issue #146)




  
然后ACTIONS里面有166个指令，绿√和红×都有。
  
能截个图或者发个链接看眼吗？

**Comment by hjenryin** [comment]
![image](https://user-images.githubusercontent.com/72179072/216073529-92c7a783-454a-4d46-b661-9a7e610c26b3.png)
umm我这里看不到 能重新发一下吗

**Comment by shilaimu21** [comment]
我是用qq邮件发的，可能这个什么网站就看不了图片吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjenryin/BCJH-Metropolis] 大佬求助 (Issue #146)




 

 umm我这里看不到 能重新发一下吗

**Comment by shilaimu21** [comment]
![image](https://user-images.githubusercontent.com/123945546/216075834-80fe4eb2-0282-4f74-bf7e-5e8e1e7e496a.png)

**Comment by shilaimu21** [comment]
![image](https://user-images.githubusercontent.com/123945546/216075965-0c108379-a372-4096-9d44-da1a12a3555a.png)

**Comment by hjenryin** [comment]
那要么索性把仓库删了重新fork吧 这样也挺方便的

> ![image](https://user-images.githubusercontent.com/123945546/216075834-80fe4eb2-0282-4f74-bf7e-5e8e1e7e496a.png)

你截图是我的仓库，你要到你的仓库里去
你的网址是https://github.com/shilaimu21/BCJH-Metropolis

**Comment by shilaimu21** [comment]
噢噢，好的&nbsp; 我明天试试，大佬早点休息啊，谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjenryin/BCJH-Metropolis] 大佬求助 (Issue #146)




 
那要么索性把仓库删了重新fork吧 这样也挺方便的
  

  
你截图是我的仓库，你要到你的仓库里去
 你的网址是https://github.com/shilaimu21/BCJH-Metropolis

**Comment by hjenryin** [comment]
不客气~如果明天问题解决了记得close这个issue👌

**Comment by shilaimu21** [comment]
大佬，搞定了，非常感谢你的付出



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjenryin/BCJH-Metropolis] 大佬求助 (Issue #146)




 
不客气~如果明天问题解决了记得close这个issue👌
