### ISSUE TITLE
按照说明更新，出现情况3

### ISSUE THREAD

**Issue by 1739344296** [hjenryin/BCJH-Metropolis#158]
按照说明更新，出现情况3

**Comment by hjenryin** [comment]
是按照readme公告进入的链接吗，先前有手动更新过吗？还是根据action的报错提示进入的呢？

**Comment by hjenryin** [comment]
> 是按照readme公告进入的链接吗，先前有手动更新过吗？还是根据action的报错提示进入的呢？

公告确实过时了，已更改

**Comment by 1739344296** [comment]
ok,麻烦了
