### ISSUE TITLE
厨具制定功能是否存在问题

### ISSUE THREAD

**Issue by Hodpel** [hjenryin/BCJH-Metropolis#162]
使用厨具定制功能后无法得到正确的计算结果 计算结果仅由未装配任何厨具计算得到.

我分别为以下厨师装配了以下厨具
|厨师|厨具|效果|
|---|---|---|
|玄离|玉兔灯|烤技法+90<br>煮类料理售价+15%|
|姒露|铁萝锤|炸技法+90<br>切类料理售价+15%|
|墨雪|木萝锤|炸技法+60<br>切类料理售价+10%|
|砚月|长青笔筒|炸技法+80<br>咸类料理售价+30%|
|司姬|开心兔餐盘|切技法+90<br>蒸类料理售价+15%|

修改的toolEquipped.hpp如下 并注释return语句
```c
    if (chef->name == "姒露") {             
        skill.ability.fry += 90; 
        skill.abilityBuff.knife += 15;
        chef->tool = NO_TOOL;
    } 
    if (chef->name == "玄离") {             
        skill.ability.bake += 90; 
        skill.abilityBuff.boil += 15;
        chef->tool = NO_TOOL;
    }  
    if (chef->name == "司姬") {             
        skill.ability.knife += 90; 
        skill.abilityBuff.steam += 15;
        chef->tool = NO_TOOL;
    }   
    if (chef->name == "砚月") {             
        skill.ability.fry += 80; 
        skill.flavorBuff.salty += 30; 
        chef->tool = NO_TOOL;
    }   
    if (chef->name == "墨雪") {             
        skill.ability.fry += 60; 
        skill.abilityBuff.knife += 10;
        chef->tool = NO_TOOL; 
    } 
```
后运行计算 得到以下结果(之一)
```
厨师：墨雪(0) -> 7 / 66125
菜谱：小熊猫泡芙；什锦火腿堡；肉末茄子
厨师：姒露(0) -> 11 / 341345
菜谱：羌族罐罐茶；老干妈蛋糕；蒜蓉芝士焗龙虾
厨师：达浪-蒸(0) -> 6 / 251250
菜谱：绝味辣卤；一点不方便面；瓜田蜜食
**************
Score: 856336
***************
```
可以发现得到的结果并不正确
![image](https://user-images.githubusercontent.com/20750355/216754279-46f95f76-2d48-4066-962a-b9c313fb781c.png)
而与去掉厨具得到的结果相同
![image](https://user-images.githubusercontent.com/20750355/216754292-a9d40b94-4abc-424e-9f60-6755e9c9184d.png)
\*本次计算结果达浪为装配厨具 但部分计算结果中有且仅有*达浪等未配置厨具者*装配了厨具 因此认为厨具定制功能中仅有`chef->tool = NO_TOOL; `生效
\*在未启用厨具定制功能时计算结果与图鉴网一致
因此厨具制定功能可能存在问题~~或者说是我的打开方式不对~~

**Comment by hjenryin** [comment]
非常感谢，你是对的。麻烦按照新的toolequipped.hpp里面的说明改一下你的配置。
