### ISSUE TITLE
关于新增的模式问题

### ISSUE THREAD

**Issue by geniusNFIL** [hjenryin/BCJH-Metropolis#163]
一个宴会模式，一个限时任务
宴会模式是厨神大赛还是？
另外，不管什么任务，都有可能出现限制要求，什么蔬菜有多少倍，肉类减分数之类的，这个可以实现吗？（基于没懂宴会模式的情况）
希望同步添加厨神大赛，限时任务，主支线等的计算，力求更新！大佬牛逼！

**Comment by geniusNFIL** [comment]
图鉴网的数据更新不及时，建议采纳：白菜菊花的数据（白菜菊花网：bcjh.xyz），可以去对比一下两个数据，看哪个更新最及时。当然，也要看能不能抓到数据。
给个大佬一个思路，见解不一定对

**Comment by hjenryin** [comment]
宴会指兔年春节、江山五媚的活动模式，分为3轮，每轮上阵3个厨师2个菜。

加成规则的配置如果针对某个厨师，见toolEquipped.hpp。如果是全局规则，在宴会模式下会由图鉴网自动生成，在限时任务中需要手动规则录入，届时会上传更新。

**Comment by hjenryin** [comment]
bcjh没有宴会计算器功能，不能导入宴会数据，所以目前用的是图鉴网。

**Comment by geniusNFIL** [comment]
大佬，先上每周的“厨神大赛”吧！每周是我们都会要用的，活动任务过了后，就没用了，嘿嘿，先搞每周的“厨神大赛”，剩下的活动任务，就到时候有活动的时候，加一个活动的接口（我想的啊，没这么简单）

**Comment by hjenryin** [comment]
这段时间也比较忙，到暑假前都不太可能更新了orz

**Comment by geniusNFIL** [comment]
额…好吧，希望大佬早点有快乐时光，冲起来！
