### ISSUE TITLE
大佬我的这里出错 麻烦帮忙看看什么原因

### ISSUE THREAD

**Issue by Bran09** [hjenryin/BCJH-Metropolis#20]
![Screenshot_20230125-134908_Chrome.jpg](https://user-images.githubusercontent.com/123462212/214490125-6280f8da-fc95-462b-a105-9fa13ec481da.jpg)

**Comment by hjenryin** [comment]
你的文件不全，可能是复制下来的，到了剪贴板长度限制了。试试从浏览器下载。

**Comment by Bran09** [comment]
> 你的文件不全，可能是复制下来的，到了剪贴板长度限制了。试试从浏览器下载。

Ok 太牛了 感谢
