### ISSUE TITLE
能否提供一个能在本地自行更改贵客配置组合的功能

### ISSUE THREAD

**Issue by 1363129424** [hjenryin/BCJH-Metropolis#216]
如题，对于之前的旧贵客，能否本地自行配置选择

**Comment by hjenryin** [comment]
第一步 修改“点此运行”文件，使其不再自动下载更新（或者如果半小时内下载过默认也是不会更新的）第二步 直接修改ruleData.json即可。这个文件里如果有多个规则默认用第一个。On Apr 5, 2024 01:02, qixuan_sun ***@***.***> wrote:
如题，对于之前的旧贵客，能否本地自行配置选择

**Comment by 1363129424** [comment]
谢谢大佬，学会了
