### ISSUE TITLE
宴会5出现bug

### ISSUE THREAD

**Issue by cuso4sean** [hjenryin/BCJH-Metropolis#30]
Chef: 宋书汐汐-炸(60)
Recipe 0: 乳鸽金丝燕窝球1: 香煎银鳕鱼2: 麻辣小鱼干
Chef: 姒露-切(0)
Recipe 0: 情人巧克力1: 雪糕刺客2: 老干妈蛋糕
Chef: 黑柏-炒(100)
Recipe 0: 蟠桃饭1: 牛肉火锅2: 灵芝空间

该方案饱食度有误

**Comment by wacilimonster310** [comment]
我也出现这个问题，饱食度少了1

**Comment by hjenryin** [comment]
在修了，大致原因是第一轮给第二轮的饱食度加成也算在第二轮的意图生效次数增加里了。

**Comment by hjenryin** [comment]
ae86ac14e7967efb492fc946f3239990b8e8507f
看看还有没有问题？

**Comment by haoyun0** [comment]
虽然很难遇到，我还是要说一下，第三关的 蒸的下道料理鲜饱食度+8，如果一道蒸下道不是鲜也会占用意图但是不加饱食度，也要break的，不能写在一起判断

**Comment by honglvdeng123** [comment]
Chef: 姒露-切(100)
Recipe 0: 佛跳墙1: 火腿蜜瓜拼盘2: 鸳鸯火锅
Chef: 大天狗-切(100)
Recipe 0: BBQ烧烤1: 莓果思慕雪2: 玫瑰鸡翅
Chef: 珊画-炸(30)
Recipe 0: 灵芝空间1: 森林烩藜麦2: 酥炸蚝配鱼子酱
**************
Score: 1869725
全修炼全专精也跑不出这么高分，不知道咋回事

**Comment by hjenryin** [comment]
> 虽然很难遇到，我还是要说一下，第三关的 蒸的下道料理鲜饱食度+8，如果一道蒸下道不是鲜也会占用意图但是不加饱食度，也要break的，不能写在一起判断

天啊牛逼啊！

**Comment by hjenryin** [comment]
> Chef: 姒露-切(100) Recipe 0: 佛跳墙1: 火腿蜜瓜拼盘2: 鸳鸯火锅 Chef: 大天狗-切(100) Recipe 0: BBQ烧烤1: 莓果思慕雪2: 玫瑰鸡翅 Chef: 珊画-炸(30) Recipe 0: 灵芝空间1: 森林烩藜麦2: 酥炸蚝配鱼子酱
> 
> Score: 1869725 全修炼全专精也跑不出这么高分，不知道咋回事

破案了，大天狗甜+120我给当成甜味料理售价+120%了

**Comment by honglvdeng123** [comment]
> > Chef: 姒露-切(100) Recipe 0: 佛跳墙1: 火腿蜜瓜拼盘2: 鸳鸯火锅 Chef: 大天狗-切(100) Recipe 0: BBQ烧烤1: 莓果思慕雪2: 玫瑰鸡翅 Chef: 珊画-炸(30) Recipe 0: 灵芝空间1: 森林烩藜麦2: 酥炸蚝配鱼子酱
> > Score: 1869725 全修炼全专精也跑不出这么高分，不知道咋回事
> 
> 破案了，大天狗甜+120我给当成甜味料理售价+120%了 修复 [0f3b430](https://github.com/hjenryin/BCJH-Metropolis/commit/0f3b43043a4e3c1ffc16ee2aadf1ad892b535a05)

我说怎么10个方案8个要大天狗哈哈
