### ISSUE TITLE
错误代码134

### ISSUE THREAD

**Issue by nanaura-komi** [hjenryin/BCJH-Metropolis#5]
![image](https://user-images.githubusercontent.com/123467485/214292457-9a258b7d-5972-49e7-82be-6d559b9149fa.png)
![image](https://user-images.githubusercontent.com/123467485/214292608-393d8ae5-7de2-44e8-a8a0-9a1edd5e041c.png)
根据教程上传了文件，但是一直运行失败，也尝试过删除重新上传了，还是不行，请问大佬有什么方法解决吗QAQ

**Comment by hjenryin** [comment]
目前尝试修复了，问题应该在于没有向actions/checkout@v2传入正确的参数，我以为默认的就可以了，以至于每次运行的都是上一个版本。但不知道为什么我之前复现不出来这个问题，看看现在解决了没有。

**Comment by hjenryin** [comment]
目前尝试修复了，问题应该在于没有向actions/checkout@v2传入正确的参数，我以为默认的就可以了，以至于每次运行的都是上一个版本。但不知道为什么我之前复现不出来这个问题，看看现在解决了没有。 8cd506721f06f66888c1ebc3ec7cc262e4197be1

**Comment by hjenryin** [comment]
#11
