### ISSUE TITLE
actions没有东西

### ISSUE THREAD

**Issue by nickpie** [hjenryin/BCJH-Metropolis#65]
fork过后 删除了userdata.json然后重新上传过后 actions里面没有东西

**Comment by hjenryin** [comment]
确定上传的是json吗？我本来想去你的fork里面看看的，是删了吗？要不然重新上传一下吧，我现在也不知道为啥

**Comment by nickpie** [comment]
> 

是json，我的fork里面data是有userdata.json的，是我重新上传的，删除原来的然后重新上传，试了好几次

**Comment by nickpie** [comment]
拉了最新的版本，就有东西了

**Comment by nickpie** [comment]
拉了最新版本，就有了，但是报错，具体错误和另外一个issues一样，[Sync main with upstream latest](https://github.com/nickpie/BCJH-Metropolis/actions/runs/4030097135/jobs/6928532757#step:4:88)
The process '/usr/bin/sh' failed with exit code 128

**Comment by wacilimonster310** [comment]
我也是一样的问题

**Comment by hjenryin** [comment]
要不这样，如果各位有空、时间方便的话加一下我qq 745938640，因为github action实在不好debug，可能需要拜托帮忙测试一下写出来的action能不能正常运行？

**Comment by hjenryin** [comment]
4f20d9247244190d1793cc4664ebefb7d08e1594
已解决 需要手动更新
特别感谢 @nickpie !
