### ISSUE TITLE
Error: The process '/usr/bin/sh' failed with exit code 128

### ISSUE THREAD

**Issue by geniusNFIL** [hjenryin/BCJH-Metropolis#74]
Error: The process '/usr/bin/sh' failed with exit code 128

这个怎么处理呢？

**Comment by hjenryin** [comment]
5839a953c2aa653dfd868c9ac4fd18d9e19faa16
看看这个可不可以。关于github action的部分实在不方便测试orz

**Comment by geniusNFIL** [comment]
已测试，问题解决！大佬牛逼！！！
