### ISSUE TITLE
提一个建议，不是bug

### ISSUE THREAD

**Issue by geniusNFIL** [hjenryin/BCJH-Metropolis#97]
建议将此自动计算放到日常任务中（周厨神大赛、限时任务，主线支线什么的），与白菜菊花作者对接，实时更新规则，加个设置，需要什么就开什么设置这种，方便我们日常完成任务什么的，彻底解放脑子，给僵尸一个新鲜的大脑！

**Comment by hjenryin** [comment]
宴会已经实现规则实时更新了，不过还在测试
https://github.com/hjenryin/BCJH-Metropolis/tree/generateRule

关于任务和厨神，因为不涉及排名不至于那么卷2333我个人暂时没有动力去实现这一点。毕竟像厨神有食材限制，修改量可能比较大，也不知道最后做出来效果会怎样。当然如果有朋友想自己动手的我也非常乐意提供帮助！

**Comment by wangzheyi** [comment]
> 宴会已经实现规则实时更新了，不过还在测试 https://github.com/hjenryin/BCJH-Metropolis/tree/generateRule
> 
> 关于任务和厨神，因为不涉及排名不至于那么卷2333我个人暂时没有动力去实现这一点。毕竟像厨神有食材限制，修改量可能比较大，也不知道最后做出来效果会怎样。当然如果有朋友想自己动手的我也非常乐意提供帮助！

我没学过编程，可以帮忙吗？简单的公式还是能看懂的

**Comment by hjenryin** [comment]
> 我没学过编程，可以帮忙吗？简单的公式还是能看懂的

没学过的话可能有点困难orz不过你想试一试的话也可以在fork上建一个branch试一试~

**Comment by geniusNFIL** [comment]
> 宴会已经实现规则实时更新了，不过还在测试 https://github.com/hjenryin/BCJH-Metropolis/tree/generateRule
> 
> 关于任务和厨神，因为不涉及排名不至于那么卷2333我个人暂时没有动力去实现这一点。毕竟像厨神有食材限制，修改量可能比较大，也不知道最后做出来效果会怎样。当然如果有朋友想自己动手的我也非常乐意提供帮助！

牛逼！

**Comment by geniusNFIL** [comment]
希望有大佬加入进来，充实工具！甚至以后实现软件自由
